### ISSUE TITLE
App crashing when using tap for Snap

### ISSUE THREAD

**Issue by iicefreeeze** [KieronQuinn/TapTap#462] opened 2022-01-24 17:02 UTC
[tap_tap_crash_report_2022-01-24T17_56_24.495.txt](https://github.com/KieronQuinn/TapTap/files/7927365/tap_tap_crash_report_2022-01-24T17_56_24.495.txt)

**Comment by KieronQuinn** [comment] 2022-01-24 17:17
Duplicate of #456

**Closed by KieronQuinn** 2022-01-24 17:17 UTC
