### ISSUE TITLE
Doesn't work after minimize or close the app

### ISSUE THREAD

**Issue by babazaneti** [KieronQuinn/TapTap#53] opened 2020-08-01 11:17 UTC
Tap tap doesn't work after I minimize or close tap tap app. Also, it doesn't wake screen for actions. But, when I unlock phone, camera app is started. Redmi Note 8

**Comment by Aniketh-Raj** [comment] 2020-08-01 12:05
Same issue in my Redmi K20 pro running Miui 12. While the Tap tap app is open the gesture works fine. the moment i close or go out of the app gesture didn't work although it simply vibrates. 
The accessibility service is On. 

@KieronQuinn let me know if you require any specific loss for this scenario. Great useful app btw. Thanks for this.. Just a little improvement and it's gonna rock

**Comment by busybox11** [comment] 2020-08-01 17:08
I also have a Redmi Note 8 but with a custom ROM (evolutionX 10) and it works. This is only MIUI related, since it is very restrictive on permissions. 

@KieronQuinn you should definetly add a disclaimer for MIUI users (and other similar Android skins in terms of restrictions) for the user to disable battery optimisations for this app or something.

**Comment by KieronQuinn** [comment] 2020-08-01 18:17
This is an MIUI bug indeed, duplicate of #48. Does it definitely work if you disable battery optimisations on MIUI?

**Closed** 2020-08-01 18:18 UTC
Labels: duplicate

**Comment by babazaneti** [comment] 2020-08-01 19:23
Same thing, even after I disable battery optimization
