### ISSUE TITLE
Download now button does not work when app detects an update.

### ISSUE THREAD

**Issue by S10MC2015** [KieronQuinn/TapTap#282] opened 2020-10-11 22:49 UTC
Even though it tries to open download link using browser it doesn't work.

This may be due to mitigations against no user interaction downloads.

**Comment by KieronQuinn** [comment] 2020-10-12 10:13
Which browser are you using? I've never had this issue on Chrome.

**Comment by S10MC2015** [comment] 2020-10-12 11:20
This is with chrome

**Comment by KieronQuinn** [comment] 2020-10-12 11:49
Unable to reproduce in that case. The download link opens a blank page, but with a popup at the bottom to download the APK. That is the mitigation, it doesn't just not download a file.

**Comment by d4rn0tt** [comment] 2020-10-15 11:10
I get this issue too, it opens up a weblink then closes

**Comment by KieronQuinn** [comment] 2021-02-07 19:30
Fixed in 0.10 beta, though you won't see a difference until the next release obviously. APK is on the releases page if you need to download it manually.

**Closed by KieronQuinn** 2021-02-07 19:30 UTC
