### ISSUE TITLE
Crash open app

### ISSUE THREAD

**Issue by TOWUK** [KieronQuinn/TapTap#494] opened 2022-02-21 05:57 UTC
downloaded your application, set everything up and started to add gestures, the app launched a certain action of the application, and it gave an error, firmware arrowos 12 android
[tap_tap_crash_report_2022-02-21T08_55_25.689.txt](https://github.com/KieronQuinn/TapTap/files/8106596/tap_tap_crash_report_2022-02-21T08_55_25.689.txt)

**Comment by KieronQuinn** [comment] 2022-02-21 10:48
The crash report shows a class that doesn't exist in the app, what action are you trying to use? Do you have steps for reproduction?

**Comment by VladWinner** [comment] 2022-02-23 01:35
@TOWUK You are using a third-party modification (moreover, an alpha version) based on an outdated build of the official VK client (for older versions of Android). The issue is definitely not caused by Tap, Tap. You should try again but with the actual untouched build of official VK client or contact the developer of this modification.

@KieronQuinn This issue can be closed as not related to Tap, Tap.

**Comment by KieronQuinn** [comment] 2022-02-23 01:55
Thanks :)

**Closed by KieronQuinn** 2022-02-23 01:55 UTC
