### ISSUE TITLE
Device has stuck in the screenshot page

### ISSUE THREAD

**Issue by nagib-18** [KieronQuinn/TapTap#385] opened 2021-03-14 19:07 UTC
The device has stopped working after taking a screenshot using it.
I had to force reboot my device.
![Screenshot_20210314-191139](https://user-images.githubusercontent.com/80645123/111080879-e09fdf00-8500-11eb-9e88-07b5eff8f49e.jpg)

**Comment by KieronQuinn** [comment] 2021-03-14 23:10
Tap, Tap does not handle the screenshot, it simply tells the system to take one. This bug is not caused by Tap, Tap, closing.

**Closed by KieronQuinn** 2021-03-14 23:10 UTC
