### ISSUE TITLE
Gestures not working after update 

### ISSUE THREAD

**Issue by GODOFEVERYTHINGVJ** [KieronQuinn/TapTap#480] opened 2022-02-01 22:14 UTC
#480 #464 #261 #126 
I m using Samsung galaxy F62..gestures have stopped working,they rarely work for which I have to literally bang my finger on the back continuously..pls fix it ASAP
If possible pls provide front screen swiping gestures ( while the screen is turned off obv) as they r not available in many phones

**Comment by KieronQuinn** [comment] 2022-02-02 01:34
Duplicate of #464, please do not open new issues when previous ones already exist and are still open.

Front swiping gestures are nothing to do with this app and are not something I'll be adding.

**Closed by KieronQuinn** 2022-02-02 01:34 UTC
