### ISSUE TITLE
App crashes after installing, can't open the app

### ISSUE THREAD

**Issue by LucasDRavarotto** [KieronQuinn/TapTap#358] opened 2021-02-08 18:43 UTC

**Comment by KieronQuinn** [comment] 2021-02-08 19:44
Please provide a logcat, I cannot do anything without that.

**Comment by LucasDRavarotto** [comment] 2021-02-08 19:49
How do I do that?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by KieronQuinn** [comment] 2021-02-08 19:58
https://www.xda-developers.com/how-to-take-logs-in-android/

**Comment by LucasDRavarotto** [comment] 2021-02-10 02:21
You know that I realized that the application stops when there is no internet connection and when there is if it works for me. Super strange but I have detected that behavior. Anyway, at the moment I can't offer you a log because I don't have a computer to give the adb permission required to be able to generate the log.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by citizenserious** [comment] 2021-02-10 02:37
I can confirm that the app crashes when there is no internet connection, or the connection is blocked at the start of the app. When the app is running then there is no internet required anymore to be stable. Looks like the update check crashes the app.

**Comment by LucasDRavarotto** [comment] 2021-02-11 17:19
Greetings again, I know that it is convenient for you to share the log to be more precise but as I was saying, due to lack of a computer I cannot, at the moment.
I present an observation that in my Motorola One Vision happens to me since I installed Tap Tap, it happens that it misconfigure the accelerometer, causing the ambient screen (Moto display) turn on and off repeatedly endlessly. I realized it was the app because when I deactivate the app it doesn't happen anymore, it's weird, I hope to explain myself, but that's what happens to me, And that switching on and off consumes a lot of battery and decalibrates the sensor, because downloading some apps to calibrate sensor shows crazy values ​​without a sense of orientation.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by drogga** [comment] 2021-02-12 13:32
> I can confirm that the app crashes at a fresh start of the app when there is no internet connection, or the connection is blocked. When the app is running then there is no internet required anymore to be stable. Looks like the update check crashes the app.

@KieronQuinn - Did you make this^ on purpose ?, because it doesn't makes any sense \ it's pointless, please fix ASAP.
Thanks in advance ;)

**Comment by drogga** [comment] 2021-02-12 13:41
> I can confirm that the app crashes at a fresh start of the app when there is no internet connection, or the connection is blocked. When the app is running then there is no internet required anymore to be stable. Looks like the update check crashes the app.

@KieronQuinn - Did you make this^ (internet connection being mandatory\a must requirement \ restriction) on purpose ?, because it doesn't makes any sense \ it's pointless and a totally unnecessary and stupid decision, please fix ASAP.
Thanks in advance ;)

**Comment by citizenserious** [comment] 2021-02-12 18:05
> > I can confirm that the app crashes at a fresh start of the app when there is no internet connection, or the connection is blocked. When the app is running then there is no internet required anymore to be stable. Looks like the update check crashes the app.
> 
> @KieronQuinn - Did you make this^ (internet connection being mandatory\a must requirement \ restriction) on purpose ?, because it doesn't makes any sense \ it's pointless and a totally unnecessary and stupid decision, please fix ASAP.
> Thanks in advance ;)

I think your use of language needs a fix ASAP.

**Comment by KieronQuinn** [comment] 2021-02-12 20:10
> > I can confirm that the app crashes at a fresh start of the app when there is no internet connection, or the connection is blocked. When the app is running then there is no internet required anymore to be stable. Looks like the update check crashes the app.
> 
> @KieronQuinn - Did you make this^ (internet connection being mandatory\a must requirement \ restriction) on purpose ?, because it doesn't makes any sense \ it's pointless and a totally unnecessary and stupid decision, please fix ASAP.
> Thanks in advance ;)

Why would I make something a requirement by making it crash if it's not provided? Don't be ridiculous.

**Comment by KieronQuinn** [comment] 2021-02-16 17:59
Fixed in 0.10.1 beta

**Closed by KieronQuinn** 2021-02-16 17:59 UTC
