### ISSUE TITLE
App crashing on s10+ and stuck on starting service

### ISSUE THREAD

**Issue by J1BBY** [KieronQuinn/TapTap#461] opened 2022-01-24 13:29 UTC
Tap, Tap Crash Report Version: 1.0 (1000) Device: SM-G975F API Version: 31 Fingerprint: samsung/beyond2lteeea/beyond2:12/SP1A.210812.016/G975FXXUEGULB:user/release-keys ------ Stack Trace ------ java.lang.SecurityException: listen 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2437) 	at android.os.Parcel.createException(Parcel.java:2421) 	at android.os.Parcel.readException(Parcel.java:2404) 	at android.os.Parcel.readException(Parcel.java:2346) 	at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenWithEventList(ITelephonyRegistry.java:1036) 	at android.telephony.TelephonyRegistryManager.listenFromCallback(TelephonyRegistryManager.java:270) 	at android.telephony.TelephonyRegistryManager.registerTelephonyCallback(TelephonyRegistryManager.java:1175) 	at android.telephony.TelephonyManager.registerTelephonyCallback(TelephonyManager.java:16398) 	at com.kieronquinn.app.taptap.utils.extensions.Extensions_CallStateKt$onCallStateChangedS$1.invokeSuspend(Extensions+CallState.kt:10) 	at com.kieronquinn.app.taptap.utils.extensions.Extensions_CallStateKt$onCallStateChangedS$1.invoke(Extensions+CallState.kt:2) 	at kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(Builders.kt:5) 	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:1) 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4) 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18) 	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:8) 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:30) 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:1) 	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:13) 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:5) 	at kotlinx.coroutines.flow.FlowKt__ShareKt.launchSharing$FlowKt__ShareKt(Share.kt:2) 	at kotlinx.coroutines.flow.FlowKt.stateIn(Unknown Source:3) 	at com.kieronquinn.app.taptap.components.columbus.gates.custom.TelephonyActivityGate.<init>(TelephonyActivityGate.kt:4) 	at com.kieronquinn.app.taptap.repositories.gates.GatesRepositoryImpl.createTapTapGate(GatesRepository.kt:22) 	at com.kieronquinn.app.taptap.service.foreground.TapTapForegroundService.access$startService(TapTapForegroundService.kt:50) 	at com.kieronquinn.app.taptap.service.foreground.TapTapForegroundService$startService$1.invokeSuspend(Unknown Source:11) 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4) 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18) 	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:5) 	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:2) 	at androidx.lifecycle.DispatchQueue$dispatchAndEnqueue$1$1.run(DispatchQueue.kt:2) 	at android.os.Handler.handleCallback(Handler.java:938) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loopOnce(Looper.java:226) 	at android.os.Looper.loop(Looper.java:313) 	at android.app.ActivityThread.main(ActivityThread.java:8633) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133) Caused by: android.os.RemoteException: Remote stack trace: 	at com.android.internal.telephony.TelephonyPermissions.enforceCarrierPrivilege(TelephonyPermissions.java:634) 	at com.android.internal.telephony.TelephonyPermissions.checkReadPhoneState(TelephonyPermissions.java:149) 	at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadPhoneState(TelephonyPermissions.java:94) 	at com.android.server.TelephonyRegistry.checkListenerPermission(TelephonyRegistry.java:3124) 	at com.android.server.TelephonyRegistry.listen(TelephonyRegistry.java:1032)

**Comment by KieronQuinn** [comment] 2022-01-24 16:46
Duplicate of #460

**Closed by KieronQuinn** 2022-01-24 16:46 UTC
