### ISSUE TITLE
Visual list bug

### ISSUE THREAD

**Issue by Andriy2** [KieronQuinn/TapTap#52] opened 2020-08-01 11:16 UTC
Open any list in application, turn screen off, turn screen on, list moved up

Screen Record: [screen-20200801-141208.zip](https://github.com/KieronQuinn/TapTap/files/5010292/screen-20200801-141208.zip)
Screenshot: [Screenshot_20200801-141537.png](https://user-images.githubusercontent.com/8833363/89100662-859df980-d401-11ea-9ce5-1cc6d0c463d7.png)

**Comment by KieronQuinn** [comment] 2020-08-01 18:20
Unable to reproduce this, please provide some more information like device and Android version.

**Comment by Andriy2** [comment] 2020-08-01 18:23
@KieronQuinn 
Google Pixel 4
Android 11 Beta 2.5

**Comment by KieronQuinn** [comment] 2021-02-07 19:41
Fixed in 0.10 beta.

**Closed by KieronQuinn** 2021-02-07 19:41 UTC
Labels: bug
